"""Initial schema — extensions, enums, and all Phase 0 tables.

Hand-written rather than autogenerated: PostGIS geography, pgvector
columns, and the HNSW index do not round-trip through Alembic
autogenerate. The canonical reference is docs/SCHEMA.sql; see
docs/adrs/0003-handwritten-spatial-vector-migrations.md.

Revision ID: 0001
Revises:
Create Date: 2026-05-26
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


EXTENSIONS = (
    "CREATE EXTENSION IF NOT EXISTS pgcrypto",
    "CREATE EXTENSION IF NOT EXISTS citext",
    "CREATE EXTENSION IF NOT EXISTS postgis",
    "CREATE EXTENSION IF NOT EXISTS vector",
)

ENUMS = (
    "CREATE TYPE post_type AS ENUM ('hangout', 'local_info')",
    "CREATE TYPE post_visibility AS ENUM "
    "('matched_only', 'friends_of_friends', 'public_in_area')",
    "CREATE TYPE hangout_status AS ENUM ('open', 'closed', 'cancelled')",
    "CREATE TYPE rsvp_status AS ENUM ('interested', 'going', 'cancelled')",
    "CREATE TYPE friendship_state AS ENUM ('pending', 'accepted', 'blocked')",
    "CREATE TYPE report_status AS ENUM ('open', 'triaging', 'actioned', 'dismissed')",
    "CREATE TYPE notif_kind AS ENUM "
    "('new_match', 'hangout_invite', 'rsvp', 'comment', 'friend_request')",
)

TABLES = (
    """
    CREATE TABLE users (
        id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        auth_provider TEXT NOT NULL,
        auth_sub      TEXT NOT NULL,
        email         CITEXT UNIQUE NOT NULL,
        phone         TEXT UNIQUE,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        deleted_at    TIMESTAMPTZ,
        UNIQUE (auth_provider, auth_sub)
    )
    """,
    """
    CREATE TABLE profiles (
        user_id           UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        display_name      TEXT NOT NULL,
        handle            CITEXT UNIQUE NOT NULL,
        avatar_url        TEXT,
        age               SMALLINT CHECK (age BETWEEN 13 AND 120),
        hometown          TEXT,
        college           TEXT,
        interests         TEXT[] NOT NULL DEFAULT '{}',
        liked_topics      TEXT[] NOT NULL DEFAULT '{}',
        bio_synthesized   TEXT,
        embedding         vector(384),
        embedding_at      TIMESTAMPTZ,
        onboarded_at      TIMESTAMPTZ,
        updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE user_locations (
        user_id      UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        geom         geography(POINT, 4326) NOT NULL,
        accuracy_m   INTEGER,
        updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE friendships (
        requester_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        addressee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        state        friendship_state NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (requester_id, addressee_id),
        CHECK (requester_id <> addressee_id)
    )
    """,
    """
    CREATE TABLE friendship_imports (
        id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        source          TEXT NOT NULL,
        imported_count  INTEGER NOT NULL,
        consent_hash    TEXT NOT NULL,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE posts (
        id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        author_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        type          post_type NOT NULL,
        visibility    post_visibility NOT NULL,
        body          TEXT NOT NULL,
        posted_geom   geography(POINT, 4326) NOT NULL,
        radius_m      INTEGER NOT NULL DEFAULT 5000,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        deleted_at    TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE post_media (
        id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
        r2_key     TEXT NOT NULL,
        mime       TEXT NOT NULL,
        width      INTEGER,
        height     INTEGER,
        sort_order INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE hangouts (
        post_id      UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
        starts_at    TIMESTAMPTZ NOT NULL,
        ends_at      TIMESTAMPTZ,
        venue        TEXT,
        max_rsvps    INTEGER,
        status       hangout_status NOT NULL DEFAULT 'open'
    )
    """,
    """
    CREATE TABLE hangout_rsvps (
        hangout_id  UUID NOT NULL REFERENCES hangouts(post_id) ON DELETE CASCADE,
        user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        status      rsvp_status NOT NULL,
        rsvped_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (hangout_id, user_id)
    )
    """,
    """
    CREATE TABLE recommendation_impressions (
        id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        candidate_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        surfaced_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        rank_position   SMALLINT NOT NULL,
        score           REAL NOT NULL,
        model_version   TEXT NOT NULL,
        breakdown_json  JSONB NOT NULL
    )
    """,
    """
    CREATE TABLE recommendation_outcomes (
        impression_id       UUID PRIMARY KEY
                            REFERENCES recommendation_impressions(id) ON DELETE CASCADE,
        viewed_at           TIMESTAMPTZ,
        profile_opened      BOOLEAN NOT NULL DEFAULT false,
        friend_request_sent BOOLEAN NOT NULL DEFAULT false,
        blocked             BOOLEAN NOT NULL DEFAULT false,
        hangout_rsvped      BOOLEAN NOT NULL DEFAULT false,
        updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE user_blocks (
        blocker_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        blocked_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (blocker_id, blocked_id),
        CHECK (blocker_id <> blocked_id)
    )
    """,
    """
    CREATE TABLE reports (
        id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        reporter_id    UUID NOT NULL REFERENCES users(id),
        target_user_id UUID REFERENCES users(id),
        target_post_id UUID REFERENCES posts(id),
        reason         TEXT NOT NULL,
        detail         TEXT,
        status         report_status NOT NULL DEFAULT 'open',
        created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        resolved_at    TIMESTAMPTZ,
        CHECK (target_user_id IS NOT NULL OR target_post_id IS NOT NULL)
    )
    """,
    """
    CREATE TABLE notifications (
        id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        kind        notif_kind NOT NULL,
        payload     JSONB NOT NULL,
        read_at     TIMESTAMPTZ,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
)

INDEXES = (
    "CREATE INDEX profiles_interests_gin ON profiles USING gin (interests)",
    "CREATE INDEX profiles_liked_gin ON profiles USING gin (liked_topics)",
    "CREATE INDEX profiles_hometown ON profiles (lower(hometown))",
    "CREATE INDEX profiles_college ON profiles (lower(college))",
    "CREATE INDEX profiles_embedding_hnsw ON profiles "
    "USING hnsw (embedding vector_cosine_ops)",
    "CREATE INDEX user_locations_gist ON user_locations USING gist (geom)",
    "CREATE INDEX friendships_addressee ON friendships (addressee_id, state)",
    "CREATE INDEX posts_geom_gist ON posts USING gist (posted_geom)",
    "CREATE INDEX posts_created ON posts (created_at DESC) WHERE deleted_at IS NULL",
    "CREATE INDEX posts_author ON posts (author_id, created_at DESC)",
    "CREATE INDEX hangout_rsvps_user ON hangout_rsvps (user_id, rsvped_at DESC)",
    "CREATE INDEX rec_imp_source ON recommendation_impressions "
    "(source_user_id, surfaced_at DESC)",
    "CREATE INDEX notifications_user_unread ON notifications "
    "(user_id, created_at DESC) WHERE read_at IS NULL",
)

# Drop order: tables first (reverse of creation to respect FKs), then enums.
DROP_TABLES = (
    "notifications",
    "reports",
    "user_blocks",
    "recommendation_outcomes",
    "recommendation_impressions",
    "hangout_rsvps",
    "hangouts",
    "post_media",
    "posts",
    "friendship_imports",
    "friendships",
    "user_locations",
    "profiles",
    "users",
)

DROP_ENUMS = (
    "notif_kind",
    "report_status",
    "friendship_state",
    "rsvp_status",
    "hangout_status",
    "post_visibility",
    "post_type",
)


def upgrade() -> None:
    for stmt in EXTENSIONS:
        op.execute(stmt)
    for stmt in ENUMS:
        op.execute(stmt)
    for stmt in TABLES:
        op.execute(stmt)
    for stmt in INDEXES:
        op.execute(stmt)


def downgrade() -> None:
    for table in DROP_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    for enum in DROP_ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
