"""Score the live ranker against baselines over recent logged outcomes.

Run as a module from ``apps/api`` (browser-only operator → run it in the
Codespace terminal)::

    python -m scripts.evaluate                 # last 7 days → docs/eval/
    python -m scripts.evaluate --days 30
    python -m scripts.evaluate --out docs/eval

It pulls every ``recommendation_impressions`` row in the window plus its
outcome, groups impressions into queries by ``(source_user_id,
surfaced_at)`` (one ``/recommendations`` call), derives graded relevance
from each outcome, and scores the live ranker against a popularity-only
and a random baseline with NDCG@10 + Recall@10 (the math lives in
``hangpost_api.recommendations.evaluation``). It writes a timestamped
markdown report under ``docs/eval/`` and prints the table.

With no outcomes yet, every relevance is 0 and the report says so
honestly rather than inventing a signal.
"""

from __future__ import annotations

import argparse
import asyncio
from collections import Counter, defaultdict
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from hangpost_api.core.db import SessionFactory
from hangpost_api.recommendations.evaluation import (
    Candidate,
    MethodScore,
    evaluate,
    relevance_from_outcome,
)
from hangpost_api.recommendations.models import (
    RecommendationImpression,
    RecommendationOutcome,
)

_METHOD_ORDER = ("live_ranker", "popularity", "random")


async def _gather(
    session: AsyncSession, since: datetime
) -> tuple[list[list[Candidate]], dict[str, int], int]:
    """Return (queries, popularity, n_impressions) for the window."""
    impressions = list(
        (
            await session.execute(
                select(RecommendationImpression).where(
                    RecommendationImpression.surfaced_at >= since
                )
            )
        )
        .scalars()
        .all()
    )
    outcomes = {
        o.impression_id: o
        for o in (await session.execute(select(RecommendationOutcome))).scalars().all()
    }

    queries: dict[tuple[str, datetime], list[Candidate]] = defaultdict(list)
    popularity: Counter[str] = Counter()
    for imp in impressions:
        popularity[str(imp.candidate_id)] += 1
        outcome = outcomes.get(imp.id)
        relevance = relevance_from_outcome(
            viewed=outcome is not None and outcome.viewed_at is not None,
            profile_opened=bool(outcome and outcome.profile_opened),
            friend_request_sent=bool(outcome and outcome.friend_request_sent),
            hangout_rsvped=bool(outcome and outcome.hangout_rsvped),
        )
        queries[(str(imp.source_user_id), imp.surfaced_at)].append(
            Candidate(str(imp.candidate_id), imp.rank_position, relevance)
        )
    return list(queries.values()), dict(popularity), len(impressions)


def render_report(
    scores: dict[str, MethodScore],
    *,
    days: int,
    generated_at: datetime,
    n_impressions: int,
) -> str:
    """Render the evaluation as a committable markdown report."""
    n_queries = next(iter(scores.values())).n_queries if scores else 0
    lines = [
        f"# Recommendation ranker evaluation — {generated_at:%Y-%m-%d}",
        "",
        f"- Window: last **{days} days**",
        f"- Impressions scored: **{n_impressions}**",
        f"- Queries (distinct `/recommendations` calls): **{n_queries}**",
        "",
        "| Method | NDCG@10 | Recall@10 |",
        "|---|---|---|",
    ]
    for name in _METHOD_ORDER:
        score = scores[name]
        lines.append(f"| `{name}` | {score.ndcg_at_10:.4f} | {score.recall_at_10:.4f} |")
    lines += [
        "",
        "Relevance grading: `friend_request_sent` / `hangout_rsvped` = 3, "
        "`profile_opened` = 2, `viewed` = 1, none = 0.",
        "",
        "_Generated by `python -m scripts.evaluate`._",
    ]
    if n_queries == 0:
        lines += [
            "",
            "> No impressions in the window yet — capture some outcomes via the "
            "`/demo` page, then re-run.",
        ]
    return "\n".join(lines) + "\n"


async def run(days: int, out_dir: Path) -> int:
    since = datetime.now(UTC) - timedelta(days=days)
    async with SessionFactory() as session:
        queries, popularity, n_impressions = await _gather(session, since)
    scores = evaluate(queries, popularity)
    generated_at = datetime.now(UTC)
    report = render_report(
        scores, days=days, generated_at=generated_at, n_impressions=n_impressions
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{generated_at:%Y-%m-%d}-eval.md"
    path.write_text(report)
    print(report)
    print(f"wrote {path}")
    return n_impressions


def main() -> None:
    parser = argparse.ArgumentParser(description="Offline ranker evaluation.")
    parser.add_argument("--days", type=int, default=7, help="lookback window in days")
    parser.add_argument(
        "--out", type=Path, default=Path("docs/eval"), help="report output directory"
    )
    args = parser.parse_args()
    asyncio.run(run(args.days, args.out))


if __name__ == "__main__":
    main()
